[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sami_program = "4Sdd8MKvmN7YXkFpPPijfur3DaDkQ72kipn68XuC7bSc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
